import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Sidebar from "./components/sidebar/Sidebar";
import Trending from "./components/Trending";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Twitter",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="h-screen bg-black">
					<div className="container h-full max-w-6xl mx-auto xl:px-30">
						<div className="grid grid-cols-4 h-full">
							<Sidebar />
							<div className="col-span-3 lg:col-span-2 border-x-[1px] border-neutral-800">
								{children}
							</div>
							<Trending />
						</div>
					</div>
				</div>
			</body>
		</html>
	);
}
